[theme]
base="light"

# Primary accent color for interactive elements.
primaryColor = '#4976E4' # couleur des bouttons

# Background color for the main content area.
# backgroundColor= '#f5f6f7' # fond de page

# Background color used for the sidebar and most interactive widgets.
# secondaryBackgroundColor = '#d2d6db'  # sidebar couleur

# Color used for almost all text.
textColor = '#222f3e' # couleur du texte

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
font = "sans serif"

[server]

# Max size, in megabytes, for files uploaded with the file_uploader.
# Default: 200
maxUploadSize = 200
